apiVersion: v1
kind: Service
metadata:
  name: modsecurity-waf
  namespace: default
  labels:
    app: modsecurity-waf
spec:
  type: LoadBalancer
  # For local/minikube: Use 'kubectl port-forward svc/modsecurity-waf 8080:80'
  # For production: LoadBalancer provides external IP
  selector:
    app: modsecurity-waf
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
