apiVersion: v1
kind: Service
metadata:
  name: backend-service-hot
  namespace: default
  labels:
    app: backend-service
    cluster: hot
spec:
  type: LoadBalancer
  # Alternative: Use NodePort with externalIPs if LoadBalancer is not available
  # type: NodePort
  # externalIPs:
  #   - <HOT_CLUSTER_NODE_IP>
  selector:
    app: backend-service-hot
    cluster: hot
  ports:
    - name: http
      port: 80
      targetPort: 8080
      # nodePort: 30080  # Uncomment if using NodePort type

