---
all:
  children:
    k8s_clusters:
      hosts:
        localhost:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: mukul
      vars:
        ansible_python_interpreter: /usr/bin/python3
